#@TYPE: Machine
#@NAME: SoMLabs IoT-BOX
#@SOC: i.MX6ULL
#@DESCRIPTION: Machine configuration for SoMLabs IoT-BOX board
#              with VisionSOM-6ULL module
#@MAINTAINER: Krzysztof Chojnowski <krzysztof.chojnowski@somlabs.com>

MACHINEOVERRIDES =. "mx6:mx6ul:mx6ull:somlabs:"

require conf/machine/include/imx-base.inc
require conf/machine/include/arm/armv7a/tune-cortexa7.inc
require conf/machine/include/somlabs.inc

UBOOT_CONFIG = "sd"
UBOOT_CONFIG[sd] = "somlabs_iot_box_6ull_defconfig,sdcard"
UBOOT_DTB_NAME = "imx6ull-somlabs-iot-box.dtb"
UBOOT_MAKE_TARGET = "u-boot.imx"
UBOOT_SUFFIX = "imx"

SERIAL_CONSOLES = "115200;ttymxc0"

IMAGE_BOOT_FILES = " \
        ${KERNEL_IMAGETYPE} \
        ${@make_dtb_boot_files(d)} \
"

KERNEL_DEVICETREE = "\
  nxp/imx/somlabs-iot-box-6ull.dtb \
"
